### ISSUE TITLE
Cross-compiling

### ISSUE THREAD

**Issue by lielfr** [aya-rs/aya-template#127]
Hi,
I'm trying to compile the ebpf part on a M1 Mac, and it seems to fail. I'm not sure how to proceed, as the cross-compilation instructions mention `cargo xtask build-ebpf`, which is not available anymore.

```bash
lielfridman@Liels-MacBook-Pro ebpf-auditer % cargo +nightly build --package ebpf-auditer-ebpf
   Compiling ebpf-auditer-ebpf v0.1.0 (/Users/lielfridman/Projects/Rust/ebpf-auditer/ebpf-auditer-ebpf)
rustc-LLVM ERROR: Global variable 'ebpf_auditer' has an invalid section specifier 'fexit/ksys_read': mach-o section specifier requires a segment and section separated by a comma.
error: could not compile `ebpf-auditer-ebpf` (bin "ebpf-auditer")

Caused by:
  process didn't exit successfully: `/Users/lielfridman/.rustup/toolchains/nightly-aarch64-apple-darwin/bin/rustc --crate-name ebpf_auditer --edition=2021 ebpf-auditer-ebpf/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=99 --crate-type bin --emit=dep-info,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=aadb8f4cc215090f -C extra-filename=-aadb8f4cc215090f --out-dir /Users/lielfridman/Projects/Rust/ebpf-auditer/target/debug/deps -C incremental=/Users/lielfridman/Projects/Rust/ebpf-auditer/target/debug/incremental -L dependency=/Users/lielfridman/Projects/Rust/ebpf-auditer/target/debug/deps --extern aya_ebpf=/Users/lielfridman/Projects/Rust/ebpf-auditer/target/debug/deps/libaya_ebpf-68eb526d29e78bb0.rlib --extern aya_log_ebpf=/Users/lielfridman/Projects/Rust/ebpf-auditer/target/debug/deps/libaya_log_ebpf-5f27b1ceeb71bbbc.rlib --extern ebpf_auditer_common=/Users/lielfridman/Projects/Rust/ebpf-auditer/target/debug/deps/libebpf_auditer_common-097da24b2d022a86.rlib --extern ebpf_auditer_ebpf=/Users/lielfridman/Projects/Rust/ebpf-auditer/target/debug/deps/libebpf_auditer_ebpf-20b34aa99a6cffda.rlib` (exit status: 101)
```

**Comment by lielfr** [comment]
I managed to get rid of the error with the following command:
```bash
cargo +nightly build --package ebpf-auditer-ebpf --release --target=bpfel-unknown-none -Z build-std=core
```

it seems like the cargo config.toml doesn't apply when trying to build from the parent crate

**Comment by tamird** [comment]
Why are you trying to compile the eBPF crate *manually*? There are two ways to compile projects generated using the template:
- using normal `cargo` commands from the root (i.e. `cargo check --package ebpf-auditor`). This intentionally doesn't compile the eBPF; it just emits an empty file to allow the userspace crate to build, and is mostly intended for development workflows like `cargo check` and clippy.
- using `xtask run`, which invokes `cargo build` with an environment variable set that causes `{{project-name}}/build.rs` to build the eBPF for real.

As far as cross-compilation, you can just use `cargo build --package {{project-name}} --target aarch64-unknown-linux-musl` from the root, and the tools will do the right thing. You can set `AYA_BUILD_EBPF=true` to build the eBPF "for real".

> as the cross-compilation instructions mention `cargo xtask build-ebpf`

Where are these instructions?

**Comment by lielfr** [comment]
yeah, the old ones were in the book. Thanks, this builds the project (had to include the linker as you mentioned in the PR).
Now I have `Error: `bpf_raw_tracepoint_open` failed`, but this is a run-time error, so I guess this one can be closed

**Comment by tamird** [comment]
Note that as of #125 we're testing all the template types in CI. I did have to make some changes to make all of them work, so you might try regenerating your project now that that PR has landed.
