### ISSUE TITLE
Inconsistent dependencies

### ISSUE THREAD

**Issue by Hanaasagi** [aya-rs/aya-template#87]
The generated code is currently not running properly.

### How to reproduce

Create a new project from template.

```
cargo generate --git https://github.com/aya-rs/aya-template
```

Select xdp type. A panic occurs when running the code. Different versions are being used for dependencies in eBPF and userland.

![2023-05-20_21-11](https://github.com/aya-rs/aya-template/assets/9482395/ff543292-dc44-44f9-87cd-d63eb46f2252)

**Comment by tamird** [comment]
We should be using aya-from-git everywhere now.
